In [128]:
import os, os.path
import pandas as pd
import numpy as np

data_dir = '../datasets/news-data'
news = []

for i, tsv_file in enumerate(os.listdir(data_dir)):
    if not tsv_file.startswith('.'):
        sample_url = os.path.join(data_dir, tsv_file)
        sample = pd.read_csv(sample_url, sep='\t', nrows=2000)
        sample = [(j, i) for j in sample['title']]

        if (i == 0):
            news = sample
        else: 
            news += sample


            
# sample = pd.read_csv('../datasets/news-data/breitbart.tsv', sep='\t', nrows=2000)

# sample = [(j, i) for j in sample['text']]
# print(sample)    

In [135]:
a = np.array([1, 0, 3])

a = np.array([1, 0, 3])
b = np.zeros((3, 4))
print(b)
b[np.arange(3), a] = 1


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [137]:
np.arange?